services:
  dashboard:
    image: ghcr.io/yikkrrtykj/vps-netwatch:latest
    container_name: vps-netwatch-dashboard
    restart: always
    volumes:
      - ./data:/dashboard/data
    ports:
      - "8008:8008"
